docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: v1/intro.md
    - "_hidden-legacy-page-links":
      - "_intro": intro.md
site_name: zend-expressive-authentication-basic
site_description: 'HTTP Basic Authentication adapter for zend-expressive-authentication.'
repo_url: 'https://github.com/zendframework/zend-expressive-authentication-basic'
